version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/.poetry
    environment:
      - ANALYST_BINANCE_API_KEY
      - ANALYST_BINANCE_SECRET_KEY
      - ANALYST_REDIS_HOST=redis
      - ANALYST_MONGODB_HOST=mongodb
      - ANALYST_MONGODB_USERNAME=user
      - ANALYST_MONGODB_PASSWORD=password123
      - ANALYST_MONGODB_DATABASE=analyst
      - ANALYST_RABBITMQ_HOST=rabbitmq
      - ANALYST_RABBITMQ_USERNAME=user
      - ANALYST_RABBITMQ_PASSWORD=password234
      - ANALYST_BOT_JWT_SECRET=test_secret
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mongodb
      - rabbitmq

  jupyter:
    build: .
    command: jupyter
    volumes:
      - .:/app
      - /app/.poetry
    environment:
      - ANALYST_BINANCE_API_KEY
      - ANALYST_BINANCE_SECRET_KEY
      - ANALYST_REDIS_HOST=redis
      - ANALYST_MONGODB_HOST=mongodb
      - ANALYST_MONGODB_USERNAME=user
      - ANALYST_MONGODB_PASSWORD=password123
      - ANALYST_MONGODB_DATABASE=analyst
      - ANALYST_BOT_JWT_SECRET=test_secret
    restart: always
    ports:
      - 8888:8888
    depends_on:
      - redis
      - mongodb
      - rabbitmq

  redis:
    image: redis:latest
    volumes:
      - ./cache_dir/redis/:/data
    command: redis-server --appendonly yes

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password123

  rabbitmq:
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password234
