version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/.poetry
    environment:
      - ANALYST_BINANCE_API_KEY
      - ANALYST_BINANCE_SECRET_KEY
      - ANALYST_REDIS_HOST=redis
    ports:
      - 8888:8888
    depends_on:
      - redis

  redis:
    image: redis:latest
    volumes:
      - ./cache_dir/redis/:/data
    command: redis-server --appendonly yes
